### ISSUE TITLE
Diagram Incorrect - Update Quadrant shows models as singular model

### ISSUE THREAD

**Issue by michaelwahlin** [learn-co-curriculum/sinatra-activerecord-reading#11]
The CRUD diagram appears to be incorrect.

Update quadrant should show: get '/models/:id/edit' and not with a singular /model
Also, should be: post '/models/:id' and not with a singular /model

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback @michaelwahlin.

We have updated the CRUD diagram and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
