### ISSUE TITLE
Missing Diagram

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/sinatra-activerecord-reading#12]
There is no diagram below this text at the end of the readme:

CONCLUSION
Remember, the purpose of this reading is to help you understand which controller actions render which views, and which views have forms that send requests to which controller actions, as we implement CRUD. Check out the diagram below for the big picture:

.....

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
