### ISSUE TITLE
Typo/odd wording

### ISSUE THREAD

**Issue by JuanGongora** [learn-co-curriculum/sinatra-activerecord-reading#13]
Under the Create header in line 21 there is some odd wording in the lists:

The get '/model/new' route **is created as block** in your controller. In this block, we can render an .erb file **that containers our form**. In this case, we'll call it new.erb.

Should be:

The get '/model/new' route is created as a block in your controller. In this block, we can render an .erb file that contains our form. In this case, we'll call it new.erb.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
