### ISSUE TITLE
Missing a forward slash

### ISSUE THREAD

**Issue by aburk3** [learn-co-curriculum/sinatra-activerecord-reading#16]
"The get 'models/:id/edit' controller action will render the edit.erb view page."

There should be a slash at `/models/:id/edit`. I figured it out after received some errors, but for the sake of consistency, it should probably lead with a slash like the other routes.

**Comment by maxwellbenton** [comment]
Hi @aburk3,

Thank you for spotting this issue and providing feedback! We have updated the materials and believe your issue to have been resolved.

Thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
