### ISSUE TITLE
Solution is not correct

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/sinatra-activerecord-reading#17]
Hey there, 

Just wanted to let you know--the solution included on this repo is not correct. I don't know if that was done intentionally to prevent students from copying and pasting the lab solution, but there is an extra space around `#{@article.id}` so it ends up looking like this `#{ @article.id }`
I mention it because I was having a difficult time with this lab, and after an hour of working I started walking myself through the provided solution to see where my code differed. I ended up correcting my code to match the solution and couldn't figure out what was going on, and still wasn't passing the lab after working on it for 2.5 hours and talking to a technical coach.

So just take that or leave it. 

Best, 
Amanda

**Comment by Sdcrouse** [comment]
Hi, @helloamandamurphy ! Did you mean to raise this issue on the "Sinatra ActiveRecord CRUD" lab? This is the "Raise an Issue" page for the "ActiveRecord in Sinatra" lesson right before it.

**Comment by drakeltheryuujin** [comment]
Hi there,

It appears that the solution branch has been restored and is now working. If this is not the case, please reopen an issue to on the [corresponding lab](https://github.com/learn-co-curriculum/sinatra-ar-crud-lab/).

Thanks for contributing!
