### ISSUE TITLE
This lesson appears out of sequence...

### ISSUE THREAD

**Issue by SwellPF** [learn-co-curriculum/sinatra-activerecord-reading#19]
This lesson is the second in the Active Record section of v7 of the web developer course.  It begins by stating that "By now you should be familiar with how to perform the basic CRUD (Create, Read, Update, Delete) actions using Active Record. Let's take a moment and review. "

It should be sequenced to be later in the curriculum (or at least remove the first two sentences).   It does do a good job of "reviewing" the information so thankfully it doesn't leave the student puzzled.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! I believe this has been resolved with V8 of the curriculum which was just released. 

![](https://curriculum-content.s3.amazonaws.com/issues/sinatra-reading.png)
![](https://curriculum-content.s3.amazonaws.com/issues/sinatra-lab.png)

As always, thanks for contributing! 💙
