### ISSUE TITLE
possible typo?

### ISSUE THREAD

**Issue by Gabrielkq** [learn-co-curriculum/sinatra-activerecord-reading#20]
I believe the code does not follow proper REST conventions. 

It is currently written thus:

form method="post" action="/models/<%= @model.id %>/delete"

However, following the diagram on RESTular, and following the conventions of I what I learned in class, it should be coded:

form method="post" action="/models/<%= @model.id %>"

without the /delete.  While this might not break the code, and Sinatra may be forgiving, at best it is bad practice, and at worst many of the "baked in" functionality may be lost.

Warm regards,

Gabriel

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
