### ISSUE TITLE
Diagram Mistake

### ISSUE THREAD

**Issue by bshap93** [learn-co-curriculum/sinatra-activerecord-reading#7]
Diagram at the bottom says post '/model/:id' instead of patch '/model/:id'

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by gb23** [comment]
To improve the content of the diagram, such that it matches up better with conventions we are learning, I recommend the following changes to the illustration in the lesson:
--In the 'Create' section of the diagram, "get '/model/new'" should be changed to "get '/model**s**/new'"
--In the 'Update' section of the diagram, "get '/model/:id/edit'" should be changed to "get '/model**s**/:id/edit'"
--Also in the 'Update' section of the diagram, "post '/model/:id'" should be changed to "**patch** '/model**s**/:id'"  (This change of "post" to "patch" was also recommended over a year ago by bshap93, see above.)

**Comment by maxwellbenton** [comment]
Thank you for spotting these issues and providing feedback, @bshap93 and @gb23 .

We have updated the diagram to reflect these corrections and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
