### ISSUE TITLE
Confusing READme route instructions

### ISSUE THREAD

**Issue by bhabig** [learn-co-curriculum/sinatra-activerecord-reading#9]
under the section 'create' header, the first bullet says "The get '/model/new' route renders the view page with that form." I am led to believe that these routes should actually look like 'get '/models/new' with a pluralized model name. it would be good to edit this here in the readme to avoid confusion moving forward (it caused problems for me in the CRUD lab that follows).

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
